Homework #4. Lists
VeraSkokova/AndroidAcademy.Fundamentals pull request #3
Opened 2020-12-06 12:25 UTC by VeraSkokova

2020-12-06 21:07 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        view.findViewById<TextView>(R.id.tv_back)
если ищешь чтобы просто поставить кликлисенер то лучше ко View касти - меньше импортов будет

2020-12-06 21:08 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +            addItemDecoration(ActorListDecoration(Metrics.dpToPx(8)))
8dp в ресурсах объяви и тут получи

2020-12-06 21:08 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +            .setOnClickListener { requireActivity().onBackPressed() }
через интрефейс

2020-12-06 21:09 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +
форматирование - одна строка между сущностями

после объявления метода лучше одну прпоусти а не пиши адаптер слитно

2020-12-06 21:17 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        val movie = movieId?.let { MovieGenerator(context).getMovieById(it) }
MovieGenerator сделайл singleton
contextn не надо - решать написать review или review надо тут -а в модельке передавать просто количество

2020-12-06 21:18 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        val movie = movieId?.let { MovieGenerator(context).getMovieById(it) }
чтобы везде не делать moview?. - сделай просто movieId?.let { MovieGenerator(context).getMovieById(it) }?.let{ movie -> ....}

2020-12-06 21:18 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        view.findViewById<ImageView>(R.id.iv_poster).setImageResource(movie?.detailsPoster ?: View.NO_ID)
если нет картинки то наверное стоит прятать постер

2020-12-06 21:19 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        val MOVIE_ID = "movie_id"
private const

2020-12-06 21:20 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +            args.putInt(MOVIE_ID, movieId)
Bundle как билдер пиши все через . просто  Bundle().put...(..).put...(...)

2020-12-06 21:21 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesList.kt
> +            layoutManager = GridLayoutManager(context, 2, RecyclerView.VERTICAL, false)
не надо волшебные числа типа 2 - сделай где0нить приватную статическую константы GRID_LAYOUT_ROW_COUNT

2020-12-06 21:22 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesList.kt
> +        super.onDetach()
сначала делаешь, а потом детачишь - поменяй местами методы - также с onStop, onDestory, onPause..
override fun onDetach() {
....
super.onDetach()
}

2020-12-06 21:23 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/MainActivity.kt
> +                .apply {
apply Лишний

2020-12-06 21:23 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/actor/Actor.kt
> +}
скобки лишние

2020-12-06 21:23 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/actor/ActorGenerator.kt
> +    private val actors = hashMapOf(
пустую стркоу перед методом - не надо слитно писать

2020-12-06 21:26 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/actor/ActorListDecoration.kt
> +        with(outRect) {
лишнее - это никак количество кода не сокращает - а ток путает - если есть логика не используй apply, with - все что меняет this - сложно читать такой код 
в основном используй ?.let{... ->

2020-12-06 21:26 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/actor/AdapterActors.kt
> +        holder.bind(actors[position])
лучше getOrNull использовать чтобы не словить OutOfBounds

2020-12-06 21:27 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/actor/AdapterActors.kt
> +    private var actors = listOf<Actor>()
пустая стркоа над и у полей лучше тип указывай

2020-12-06 21:29 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/actor/AdapterActors.kt
> +    fun bindActors(actors: List<Actor>) {
ты их сетишь а не байндишь - лучше стандартно updateActors или updateData

2020-12-06 21:30 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/movie/MovieGenerator.kt
> +    private val emptyDuration = "-"
в константы

2020-12-06 21:31 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/movie/MovieGenerator.kt
> +    fun getMovies(): List<Movie> = movies.values.toList()
я бы сделал листом и не мудрил - но можно и так оставить

2020-12-06 21:31 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/movie/MoviesListDecoration.kt
> +            right = (column + 1) * spacing / columns
spacing/columns можно один раз посчитать

2020-12-06 21:33 UTC, konstzv commented on app/src/main/res/layout/view_holder_actor.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
кажется тут linearLayout хватит и всякие цепочки лишнее

2020-12-06 21:34 UTC, konstzv commented on app/src/main/res/layout/view_holder_movie.xml
> +<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
линтер обрабатывай или глуши

2020-12-06 21:35 UTC, konstzv requested changes
Нужны правки

2020-12-19 09:40 UTC, VeraSkokova commented on app/src/main/res/layout/view_holder_actor.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
У меня с ConstraintLayout лучше получилось привязать TextView к границам картинки, без constaint'ов оно с отступом почему-то

2020-12-19 09:42 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/movie/AdapterMovies.kt
> +        reviews.text = itemView.context.resources.getQuantityString(R.plurals.movie_reviews, movie.reviews, movie.reviews)
Ты говорил, что в onBindViewHolder не нужно делать тяжелых операций. А вот такие штуки допустимы? Если нет, то куда это можно вынести?

2020-12-19 09:57 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +            args.putInt(MOVIE_ID, movieId)
Можешь какой-нибудь пример скинуть, пожалуйста? putInt возвращает Unit, от него не получается какой-нибудь другой put вызвать. Или надо подключить либу какую-то?

2020-12-23 15:04 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/movie/AdapterMovies.kt
> +        reviews.text = itemView.context.resources.getQuantityString(R.plurals.movie_reviews, movie.reviews, movie.reviews)
ну операции с ресурсами нежелательны так как тяжелые, но конкретно тут можно оставить так как не просто заменить

2020-12-23 15:04 UTC, merged