Multithreading
VeraSkokova/AndroidAcademy.Fundamentals pull request #5
Opened 2020-12-20 18:31 UTC by VeraSkokova

2020-12-23 15:07 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main + exceptionHandler)
пустая строка выше

2020-12-23 15:29 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +                loadMovie(movieId, context!!)?.let { movie ->
requestContext

2020-12-23 15:30 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        val movieId = arguments?.getInt(MOVIE_ID)
если id нет то возможно стоит выкинуть ошибку или закрыть экран

2020-12-23 15:31 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesList.kt
> +        scope = CoroutineScope(SupervisorJob() + Dispatchers.Main + exceptionHandler)
зачем это?

2020-12-23 15:31 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        Log.w(ERROR_TAG, "CoroutineExceptionHandler got $exception in $coroutineContext")
Log.e наверное

2020-12-23 15:32 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesList.kt
> +        context?.let {
requestContext

2020-12-23 15:33 UTC, konstzv requested changes
поправь замечания

2020-12-26 16:17 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesList.kt
> +        scope = CoroutineScope(SupervisorJob() + Dispatchers.Main + exceptionHandler)
Так в воркшопе было, и в моем случае, т.к в MainActivity#onClick был replace, то у FragmentMoviesList вызывался onDestroyView, и при навигации назад на отмененном scope уже нельзя было запустить корутину. Заменила replace на add, стало не нужно, убрала

2020-12-26 16:47 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/FragmentMoviesDetails.kt
> +        if (movieId == null) {
можно и через movieId?.let{}?:run{}
но и так ок

2020-12-26 16:47 UTC, konstzv approved these changes

2020-12-27 19:40 UTC, merged