Homework #6. Ui architectures
VeraSkokova/AndroidAcademy.Fundamentals pull request #6
Opened 2020-12-29 14:33 UTC by VeraSkokova

2021-01-11 08:15 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +            viewModel.getMovieDetails(movieId)
viewModel:: getMovieDetails

2021-01-11 08:19 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +                is Resource.Error -> Toast.makeText(context, resource.message!!, Toast.LENGTH_SHORT)
зачем делать поля нулабельные, а потом делать еще и !!, сделай ненулабельными

2021-01-11 08:21 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/Resource.kt
> +    val message: String? = null
не нужен базывой конструктор и почему это ресурс называется?

2021-01-11 08:22 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesList.kt
> +        viewModel.getMovies()
перенеси загрузку в initi viewmodel, не надо из view ей командовать так

2021-01-11 08:22 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieDetailsViewModel.kt
> +        private const val NULL_MESSAGE = "There is no movie with this id"
сообщения логово обычно хардкодят, не выносят. Но ок если вынесла

2021-01-11 08:25 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieDetailsViewModel.kt
> +                mutableMovieDetailsLiveData.value = Resource.Error(NULL_MESSAGE)
проще типа так - лучше видно что меняется и от какого условия -
```
   mutableMovieDetailsLiveData.value = movie?.let {
                Resource.Success(movie)
            } ?: run {
                Resource.Error(NULL_MESSAGE)
            }

2021-01-11 08:28 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieListViewModel.kt
> +    fun getMovies(): LiveData<Resource<List<Movie>>> {
переделай этот метод, вызывай логику по загрузке из viewmodel, а не из view

2021-01-11 08:29 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesList.kt
> +                    is Resource.Success -> moviesAdapter?.updateMovies(it.data!!)
it не используй, !! не используй

2021-01-11 08:31 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesList.kt
> +        viewModel.moviesLiveData.observe(
А почему в одном месте в onStart/ а в другом в onViewCreated подписываешься?

2021-01-11 08:31 UTC, konstzv requested changes
Поправь замечания

2021-01-11 15:42 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/data/Resource.kt
> +    val message: String? = null
Вот отсюда взяла, название не меняла
https://developer.android.com/jetpack/guide#addendum

2021-01-17 12:58 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +            viewModel.getMovieDetails(movieId)
Не сработало почему-то, метод не вызывается,  с чем это может быть связано?

2021-01-20 19:05 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +            viewModel.getMovieDetails(movieId)
(viewModel:: getMovieDetails) - я вот так имел ввиду - если фигурные оставить то не будет работать

2021-01-20 19:07 UTC, konstzv approved these changes
поправь скобки и мерж

2021-01-24 22:05 UTC, konstzv approved these changes

2021-02-02 11:38 UTC, merged