Homework #7. Network
VeraSkokova/AndroidAcademy.Fundamentals pull request #7
Opened 2021-01-18 15:49 UTC by VeraSkokova

2021-01-22 17:24 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/business/ActorsInteractor.kt
> +        val actors = actorsRepository.getActors(movieId)
тут получаешь response - эт не явно не по названию метода, не по названию переменной. Я бы инкапсулировал получение и конвертацию актеров в репозитории и там же создал маппер. Маппер лучше  тоже создавать один раз как и репозиторий - передавать в конструктор. Да возможно метод вызовется один раз , но в будущем может быть и несколько - и на каждый вызов будет создаваться маппер - хоть одного достаточно

2021-01-22 17:26 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/business/ConfigurationInteractor.kt
> +        configurationConverter.toConfiguration(configuration)
тут тоже самое + configuration не очень понятное название - я бы подумал над другим названием - чтоб сразу было понятно

2021-01-22 17:26 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/business/MovieDetailsInteractor.kt
> +        movieMapper.toMovie(loadMovie)
тож самое

2021-01-22 17:27 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/business/MovieListInteractor.kt
> +            val loadGenres = genresRepository.loadGenres()
переименуй переменную

2021-01-22 17:31 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/ActorsRepository.kt
> +class ActorsLoader : ActorsRepository {
обычно называют или по типа репозитория - DatabaseActorsRepositoryImpl или ActorsRepositoryImpl.

2021-01-22 17:34 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/MovieLoad.kt
>  interface MovieListRepository {
раздели на разные файлы или объедини сущности

2021-01-22 17:36 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/converter/ConfigurationMapper.kt
> +        return baseUrl + sizes[sizes.size - 1]
sizes могут быть пустыми?
есть функция last или lastOrNull

2021-01-22 17:37 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/converter/MovieMapper.kt
> +        minimumAge = if (jsonMovie.adult) 16 else 13,
числа в константы и ниже

2021-01-22 17:40 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/converter/MovieMapper.kt
> +                genresMap[it] ?: throw IllegalArgumentException("Genre not found")
зачем лишний map - эт создание лишнего листа - упакуй все в joinToString

2021-01-22 17:41 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/converter/MovieMapper.kt
> +        genres = jsonMovie.genres.joinToString { it.name }
дубляж убери из класса - может методы объединить может

2021-01-22 17:42 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/model/TmdbConfiguration.kt
> +data class TmdbConfiguration(
папка не соотвествует файлу

2021-01-22 17:42 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/model/TmdbConfiguration.kt
> +data class TmdbConfiguration(
зачем data?

2021-01-22 17:43 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/network/ActorsResponse.kt
> +class ActorsItemResponse(
дели на разные файлы - ну не удобно ж

2021-01-22 17:44 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/network/RetrofitModule.kt
> +    private val json = Json {
зачем в поле - вынеси в метод создания retrofit через = run{}

2021-01-22 17:45 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +    private val configurationViewModel: TmdbConfigurationViewModel by viewModels { MovieViewModelFactory() }
зачем три инстанса MovieViewModelFactory создавать

2021-01-22 17:47 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieListViewModel.kt
init {	    init {
        if (mutableMoviesLiveData.value == null) {	        if (mutableMoviesLiveData.value == null) {

а как оно не null может быть

2021-01-22 17:50 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +        backdropImageUrl?.apply {
зачем apply - тут if хватит

2021-01-22 17:51 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +            updatePoster(movie, view, backdropImageUrl)
ты передаешь события а не задания, это можно в init

2021-01-22 17:53 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +            actorsViewModel.getMovieActors(movieId)
лучше айди передай через файбрику в модель а загрузку в init

2021-01-22 17:54 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesDetails.kt
> +            actorsViewModel.getMovieActors(movieId)
не уверен что разделение вью моделей полезно - как ты общий индикатор закгрузки например покажешь или будешь в какждом блоке его показывать

2021-01-22 17:56 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/FragmentMoviesList.kt
> +            getMovies()
это подписка же -а не гет - apply также не нужен

2021-01-22 17:57 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/ui/MainActivity.kt
> +    override fun setBaseImageUrls(backdropUrl: String, posterUrl: String, profileUrl: String) {
это не в активити должно быть а в репозитории,  закрытом интерфейсом

2021-01-22 17:57 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/ActorsViewModel.kt
> +            exception.message ?: "An error occurred while loading movie details. Please, check logs"
в константу если захардкожено

2021-01-22 17:58 UTC, konstzv commented on app/src/main/res/values/strings.xml
> +    <!--Actors-->
не над с обеих сторо - с верху понятно

2021-01-22 17:58 UTC, konstzv requested changes
поправь замечания

2021-02-02 12:33 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/data/converter/MovieMapper.kt
> +        genres = jsonMovie.genres.joinToString { it.name }
Дубляж в плане того, что в двух методах был joinToString? Сейчас получше по-моему, или нет?

2021-02-02 12:34 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/data/model/TmdbConfiguration.kt
> +data class TmdbConfiguration(
Случайно было, убрала

2021-02-08 16:12 UTC, merged