Homework #8. Persistency
VeraSkokova/AndroidAcademy.Fundamentals pull request #8
Opened 2021-02-07 10:04 UTC by VeraSkokova

2021-02-08 17:40 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/business/ActorsInteractor.kt
> +        actorsCacheRepository
?

2021-02-08 17:42 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/business/ImageLoadingInfoInteractor.kt
> +        cachedRepository.getImageLoadingInfo() ?: run {
run{ лишний - a?: b?: c

2021-02-08 17:46 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieDetailsViewModel.kt
> +                Resource.Success(MovieDetails(loadedMovie, loadedActors))
странаня логика кэширования. Я бы выбрал из двух способ - 1)грузишь всегда по сети - если ошибка то грузишь из кэша. 2)Ну или наоборот из кэша грузишь и только если ошибка или его нет или он просрочился то грузить из сети

2021-02-08 17:47 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieDetailsViewModel.kt
> +                Resource.Success(MovieDetails(loadedMovie, loadedActors))
плюс эта логика как по мне не особо задача презентера - скорее интерактора - там ты связываешь несколько репозиториев

2021-02-08 17:48 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieDetailsViewModel.kt
> +                Resource.Success(MovieDetails(loadedMovie, loadedActors))
я бы сделал модельку этого экрана с актерами и инфой о фильме которая собирется в интеракторе и одним классом сюда прилетит

2021-02-08 17:50 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieListViewModel.kt
> +            mutableMoviesLiveData.value = Resource.Success(loadedMovies)
тоже самое насчет логики кэша

2021-02-08 17:50 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieViewModelFactory.kt
> +                NetworkMovieListRepository(JsonMovieMapper(), DbGenresRepository(EntityGenreMapper())),
форматироваие

2021-02-08 17:54 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/ImageLoadingInfoRepository.kt
> +internal const val URLS_SAVED = "urls_saved"
это все должно быть в одном репозитории и приватно

2021-02-08 17:55 UTC, konstzv requested changes
поправь замечания

2021-02-08 17:57 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/GenresCachingRepository.kt
> +        return savedGenres.map { mapper.toGenre(it) }
mapper:toGenre - ниже также

2021-02-08 17:58 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/GenresRepository.kt
> +        return RetrofitModule.moviesApi.getGenres().genres.map { jsonMapper.toGenre(it) }
апи можно передать в конструктор - будет более явные зависимости

2021-02-08 17:59 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/mapper/JsonMovieMapper.kt
> +        const val NOT_ADULT_AGE = 13
почему публичные?

2021-02-08 18:00 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/persistent/ActorsDao.kt
> +    @Query("DELETE FROM " + MoviesDatabaseContract.Actors.TABLE_NAME)
сюда название таблиц, полей из подсказок лучше добавлять - не надо константы

2021-02-08 18:02 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/persistent/ActorsDao.kt
> +    @Query("DELETE FROM " + MoviesDatabaseContract.Actors.TABLE_NAME)
и везде также - убери эти константы вообще
название полей напиши просто текстом
все равно из этого сгенерятся файлы при компиляции и никакой оптимизации за счет констант не будет, наоборот они будут висеть бесполещные

2021-02-08 18:02 UTC, konstzv commented on app/src/main/java/ru/skokova/android_academy/data/persistent/MoviesDatabaseContract.kt
> +}
удали класс и захардколь все

2021-02-14 09:04 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/business/ActorsInteractor.kt
> +        actorsCacheRepository
Случайно

2021-02-14 09:05 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/viewmodel/MovieDetailsViewModel.kt
> +                Resource.Success(MovieDetails(loadedMovie, loadedActors))
Это я так почему-то условие поняла
Поправила по первому варианту

2021-02-14 09:06 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/data/ImageLoadingInfoRepository.kt
> +internal const val URLS_SAVED = "urls_saved"
Вообще один репозиторий лучше оставить?
Я пока сделала просто приватные константы

2021-02-14 09:06 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/data/mapper/JsonMovieMapper.kt
> +        const val NOT_ADULT_AGE = 13
Поправила

2021-02-14 09:06 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/data/persistent/ActorsDao.kt
> +    @Query("DELETE FROM " + MoviesDatabaseContract.Actors.TABLE_NAME)
Из аннотаций убрала

2021-02-14 09:07 UTC, VeraSkokova commented on app/src/main/java/ru/skokova/android_academy/data/persistent/MoviesDatabaseContract.kt
> +}
Лучше вообще убрать все-все?

2021-03-05 14:58 UTC, merged